# Generated by Django 3.2 on 2022-07-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REDDIT_CLIENT_ID', models.CharField(max_length=200)),
                ('REDDIT_CLIENT_SECRET', models.CharField(max_length=300)),
                ('REDDIT_USERNAME', models.CharField(max_length=115)),
                ('REDDIT_PASSWORD', models.CharField(max_length=30)),
                ('SUBREDDIT', models.CharField(max_length=115)),
                ('MAX_COMMENT_LENGTH', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
