# Generated by Django 3.2 on 2022-07-10 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BotApp', '0003_auto_20220710_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec',
            name='REDDIT_PASSWORD',
        ),
        migrations.RemoveField(
            model_name='spec',
            name='REDDIT_USERNAME',
        ),
    ]
