# Generated by Django 3.2 on 2022-07-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotApp', '0004_auto_20220710_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REDDIT_CLIENT_ID', models.CharField(max_length=200)),
                ('REDDIT_CLIENT_SECRET', models.CharField(max_length=300)),
                ('MAX_COMMENT_LENGTH', models.IntegerField()),
                ('POST_URL', models.URLField(blank=True, max_length=500)),
                ('flag', models.IntegerField(default=0)),
                ('SELECTED_VOICE', models.CharField(max_length=115)),
            ],
        ),
        migrations.CreateModel(
            name='customspecvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_voices', models.CharField(max_length=115)),
                ('FilterType', models.CharField(choices=[('Brian', 'Brian (English, British)'), ('Amy', 'Amy (English, British)'), ('Emma', 'Emma (English, British)'), ('Geraint', 'Geraint (English, Welsh)'), ('Russell', 'Russell (English, Australian)'), ('Nicole', 'Nicole (English, Australian)'), ('Joey', 'Joey (English, American)'), ('Justin', 'Justin (English, American)'), ('Matthew', 'Matthew (English, American)'), ('Ivy', 'Ivy (English, American) '), ('Joanna', 'Joanna (English, American) '), ('Kendra', 'Kendra (English, American)'), ('Kimberly', 'Kimberly (English, American)'), ('Salli', 'Salli (English, American)'), ('Raveena', 'Raveena (English, Indian) '), ('Aditi', 'Aditi (+English) (Hindi)')], max_length=360)),
            ],
        ),
        migrations.CreateModel(
            name='voices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_voices', models.CharField(max_length=115)),
                ('FilterType', models.CharField(choices=[('Brian', 'Brian (English, British)'), ('Amy', 'Amy (English, British)'), ('Emma', 'Emma (English, British)'), ('Geraint', 'Geraint (English, Welsh)'), ('Russell', 'Russell (English, Australian)'), ('Nicole', 'Nicole (English, Australian)'), ('Joey', 'Joey (English, American)'), ('Justin', 'Justin (English, American)'), ('Matthew', 'Matthew (English, American)'), ('Ivy', 'Ivy (English, American) '), ('Joanna', 'Joanna (English, American) '), ('Kendra', 'Kendra (English, American)'), ('Kimberly', 'Kimberly (English, American)'), ('Salli', 'Salli (English, American)'), ('Raveena', 'Raveena (English, Indian) '), ('Aditi', 'Aditi (+English) (Hindi)')], max_length=360)),
            ],
        ),
        migrations.AddField(
            model_name='spec',
            name='FilterType',
            field=models.CharField(choices=[('Hot', 'Hot'), ('New', 'New'), ('Top', 'Top'), ('Top-Now', 'Top-Now'), ('Top-Today', 'Top-Today'), ('Top-ThisWeek', 'Top-ThisWeek'), ('Top-ThisMonth', 'Top-ThisMonth'), ('Top-ThisYear', 'Top-ThisYear'), ('Top-AllTime', 'Top-AllTime')], default='Hot', max_length=60),
        ),
        migrations.AddField(
            model_name='spec',
            name='POST_URL',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='spec',
            name='SELECTED_VOICE',
            field=models.CharField(blank=True, max_length=115),
        ),
    ]
