# Generated by Django 3.2 on 2022-07-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotApp', '0005_auto_20220718_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='FilterType',
            field=models.CharField(choices=[('Hot', 'Hot'), ('New', 'New'), ('Top', 'Top'), ('Top-Now', 'Top-Now'), ('Top-Today', 'Top-Today'), ('Top-ThisWeek', 'Top-ThisWeek'), ('Top-ThisMonth', 'Top-ThisMonth'), ('Top-ThisYear', 'Top-ThisYear'), ('Top-AllTime', 'Top-AllTime')], max_length=60),
        ),
        migrations.AlterField(
            model_name='spec',
            name='SELECTED_VOICE',
            field=models.CharField(max_length=115),
        ),
    ]
