# Generated by Django 3.2 on 2022-07-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotApp', '0006_auto_20220718_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
