# Generated by Django 3.2 on 2022-07-19 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BotApp', '0007_login_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec',
            name='POST_URL',
        ),
    ]
