# Generated by Django 3.2 on 2022-07-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotApp', '0008_remove_spec_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customspec',
            name='BACKGROUND_VIDEO_URL',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='spec',
            name='BACKGROUND_VIDEO_URL',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
