# Generated by Django 3.2 on 2022-07-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotApp', '0009_auto_20220719_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='REDDIT_CLIENT_ID',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='login',
            name='REDDIT_CLIENT_SECRET',
            field=models.CharField(default='', max_length=300),
        ),
    ]
