# Generated by Django 3.2 on 2022-07-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BotApp', '0010_auto_20220719_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customspec',
            name='REDDIT_CLIENT_ID',
        ),
        migrations.RemoveField(
            model_name='customspec',
            name='REDDIT_CLIENT_SECRET',
        ),
        migrations.RemoveField(
            model_name='spec',
            name='REDDIT_CLIENT_ID',
        ),
        migrations.RemoveField(
            model_name='spec',
            name='REDDIT_CLIENT_SECRET',
        ),
    ]
