# Generated by Django 3.2 on 2022-07-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotApp', '0011_auto_20220719_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='FilterType',
            field=models.CharField(choices=[('Hot', 'Hot'), ('New', 'New'), ('Top-Now', 'Top-Now'), ('Top-Today', 'Top-Today'), ('Top-ThisWeek', 'Top-ThisWeek'), ('Top-ThisMonth', 'Top-ThisMonth'), ('Top-ThisYear', 'Top-ThisYear'), ('Top-AllTime', 'Top-AllTime')], max_length=60),
        ),
    ]
