# Generated by Django 3.2 on 2022-07-20 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BotApp', '0012_alter_spec_filtertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customspecvoices',
            name='available_voices',
        ),
        migrations.RemoveField(
            model_name='voices',
            name='available_voices',
        ),
    ]
